dist: xenial
language: python
sudo: false

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8-dev
  - pypy2.7-6.0
  - pypy3.5

env:
  global:
    - ASTTOKENS_SLOW_TESTS=1
    - COVERALLS_PARALLEL=true

install:
  - pip install coveralls
  - pip install .[test]

script:
  - travis_wait 30 coverage run --include='asttokens/*' -m pytest
  - coverage report -m

after_success:
  - coveralls
